from __future__ import annotations

import importlib

__all__ = [
    "AnthropicMessageBuilder",
    "ArtifactKindDescriptor",
    "BaseToolHarness",
    "CATALOG_TOOL_NAMES",
    "DeferredToolRecord",
    "execute_confirmable_tool_call",
    "GeminiMessageBuilder",
    "HistoryPayloadOptimizer",
    "HumanInputResumeHarness",
    "inject_observation",
    "NormalizedToolHistoryRecord",
    "OBSERVATION_MAX_OUTPUT_TOKENS",
    "OBSERVATION_RECENT_MESSAGES",
    "OBSERVATION_SYSTEM_PROMPT",
    "OllamaMessageBuilder",
    "observation_token_state",
    "OpenAIMessageBuilder",
    "ProviderMessageBuilder",
    "TOOLKIT_ACTIVATE_TOOL_NAME",
    "TOOLKIT_DEACTIVATE_TOOL_NAME",
    "TOOLKIT_DESCRIBE_TOOL_NAME",
    "TOOLKIT_LIST_ACTIVE_TOOL_NAME",
    "TOOLKIT_LIST_TOOL_NAME",
    "Tool",
    "tool",
    "ToolBatchState",
    "ToolConfirmationRequest",
    "ToolConfirmationResponse",
    "ToolConfirmationPolicy",
    "ToolContext",
    "ToolDiscoveryConfig",
    "ToolDiscoveryRuntime",
    "ToolDescriptor",
    "SkillDescriptor",
    "ToolExecutionHarness",
    "ToolOutputBudget",
    "ToolOutputManagementError",
    "ToolOutputManager",
    "ToolOutputPolicy",
    "ToolOutputPolicyVersionError",
    "ToolOutputProjection",
    "ToolOutputReadError",
    "ToolOutputReadRequest",
    "ToolExecutionContext",
    "ToolExecutionOutcome",
    "ToolExposurePlan",
    "ToolExposureRuntime",
    "ToolHarness",
    "ToolHistoryOptimizationContext",
    "ToolOptimizerConfig",
    "ToolParameter",
    "ToolObservationRunner",
    "ToolPromptHarness",
    "ToolPromptSpec",
    "ToolRegistryConfig",
    "ToolResultBudgetConfig",
    "ToolResultBudgetController",
    "ToolResultBudgetOutcome",
    "ToolResultBudgetStats",
    "ToolRuntimeOutcome",
    "ToolRuntimePlugin",
    "Toolkit",
    "ToolkitCatalogConfig",
    "ToolkitCatalogRuntime",
    "ToolkitDescriptor",
    "ToolkitRegistry",
    "build_visible_toolkits",
    "extract_toolkit_catalog_token",
    "get_provider_message_builder",
    "get_toolkit_metadata",
    "list_artifact_kinds",
    "list_toolkits",
    "render_tool_prompt_block",
    "render_tool_prompt_entry",
]

_EXPORT_TO_MODULE = {
    "CATALOG_TOOL_NAMES": ".catalog",
    "TOOLKIT_ACTIVATE_TOOL_NAME": ".catalog",
    "TOOLKIT_DEACTIVATE_TOOL_NAME": ".catalog",
    "TOOLKIT_DESCRIBE_TOOL_NAME": ".catalog",
    "TOOLKIT_LIST_ACTIVE_TOOL_NAME": ".catalog",
    "TOOLKIT_LIST_TOOL_NAME": ".catalog",
    "ToolkitCatalogConfig": ".catalog",
    "ToolkitCatalogRuntime": ".catalog",
    "build_visible_toolkits": ".catalog",
    "extract_toolkit_catalog_token": ".catalog",
    "BaseToolHarness": ".base",
    "ToolContext": ".base",
    "ToolHarness": ".base",
    "ToolExecutionOutcome": ".confirmation",
    "execute_confirmable_tool_call": ".confirmation",
    "tool": ".decorators",
    "ToolExecutionHarness": ".execution",
    "ToolOutputBudget": ".output_management",
    "ToolOutputManagementError": ".output_management",
    "ToolOutputManager": ".output_management",
    "ToolOutputPolicy": ".output_management",
    "ToolOutputPolicyVersionError": ".output_management",
    "ToolOutputProjection": ".output_management",
    "ToolOutputReadError": ".output_management",
    "ToolOutputReadRequest": ".output_management",
    "HumanInputResumeHarness": ".human_input",
    "AnthropicMessageBuilder": ".messages",
    "GeminiMessageBuilder": ".messages",
    "OpenAIMessageBuilder": ".messages",
    "OllamaMessageBuilder": ".messages",
    "ProviderMessageBuilder": ".messages",
    "get_provider_message_builder": ".messages",
    "HistoryPayloadOptimizer": ".models",
    "NormalizedToolHistoryRecord": ".models",
    "ToolConfirmationRequest": ".models",
    "ToolConfirmationPolicy": ".models",
    "ToolConfirmationResponse": ".models",
    "ToolExecutionContext": ".models",
    "ToolHistoryOptimizationContext": ".models",
    "ToolParameter": ".models",
    "ToolPromptSpec": ".models",
    "OBSERVATION_MAX_OUTPUT_TOKENS": ".observation",
    "OBSERVATION_RECENT_MESSAGES": ".observation",
    "OBSERVATION_SYSTEM_PROMPT": ".observation",
    "ToolObservationRunner": ".observation",
    "inject_observation": ".observation",
    "observation_token_state": ".observation",
    "ToolPromptHarness": ".prompting",
    "render_tool_prompt_block": ".prompting",
    "render_tool_prompt_entry": ".prompting",
    "DeferredToolRecord": ".discovery",
    "ToolDiscoveryConfig": ".discovery",
    "ToolDiscoveryRuntime": ".discovery",
    "ToolExposurePlan": ".exposure",
    "ToolExposureRuntime": ".exposure",
    "ToolOptimizerConfig": ".exposure",
    "ToolDescriptor": ".registry",
    "SkillDescriptor": ".models",
    "ArtifactKindDescriptor": ".registry",
    "ToolRegistryConfig": ".registry",
    "ToolResultBudgetConfig": ".result_budget",
    "ToolResultBudgetController": ".result_budget",
    "ToolResultBudgetOutcome": ".result_budget",
    "ToolResultBudgetStats": ".result_budget",
    "ToolkitDescriptor": ".registry",
    "ToolkitRegistry": ".registry",
    "get_toolkit_metadata": ".registry",
    "list_artifact_kinds": ".registry",
    "list_toolkits": ".registry",
    "ToolRuntimeOutcome": ".runtime",
    "ToolRuntimePlugin": ".runtime",
    "Tool": ".tool",
    "Toolkit": ".toolkit",
    "ToolBatchState": ".types",
}

tool = importlib.import_module(".decorators", __name__).tool


def __getattr__(name: str):
    if name == "tool":
        return tool
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(name)
    module = importlib.import_module(module_name, __name__)
    return getattr(module, name)


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
